### ISSUE TITLE
Addon options passed in to treeForBrowserFetch are undefined

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-fetch#200]
Options passed here: https://github.com/ember-cli/ember-fetch/blob/master/index.js#L111 seem to be undefined.

Stumbled onto this here https://github.com/sethwebster/ember-cli-new-version/issues/55

**Comment by xg-wang** [comment]
@knownasilya 
`this._super.included.apply(this, arguments);` should be called at beginning of `included` here https://github.com/sethwebster/ember-cli-new-version/blob/v1.4.2/index.js#L12 otherwise sub-dependency's `included` hook won't be triggered.

BTW `ember-fetch` bundles assets so it should lives in `devDependencies` and requires host app to install it as top-level dep.

**Comment by knownasilya** [comment]
Thanks for catching this. I'll update the addon to handle this case.
