### ISSUE TITLE
Deprecation for ember data mixin for older ED versions

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-fetch#391]
After https://github.com/ember-cli/ember-fetch/pull/308, we get a lot of deprecation warnings in our app:

```
DEPRECATION: FetchAdapter is deprecated, it is no longer required for ember-data>=3.9.2 [deprecation id: deprecate-fetch-ember-data-support]
```

We cannot easily update ED (for other reasons), so we are currently using 3.4.x. 

The deprecation warning incorrectly suggests that we should stop using the FetchAdapter. I guess the deprecation should only be shown for users with ember-data >= 3.10?

**Comment by Turbo87** [comment]
I'm seeing the same issue on https://github.com/rust-lang/crates.io

/cc @xg-wang

**Comment by xg-wang** [comment]
@stefanpenner https://github.com/ember-cli/ember-fetch/pull/447 will be contradicting the request here to only log deprecation for newer ember-data versions. If we're going to drop the mixin, answer to this issue is to [manually silence the deprecation](https://api.emberjs.com/ember/release/functions/@ember%2Fdebug/registerDeprecationHandler) until ember-data upgrade is finished.

@mydea @Turbo87 what do you think?

**Comment by mydea** [comment]
I guess that's OK, maybe not ideal but workable!
