### ISSUE TITLE
Could not find module `rsvp` imported from `fetch`

### ISSUE THREAD

**Issue by mydea** [ember-cli/ember-fetch#622]
When trying to setup embroider for our app, I get this error:

```
Uncaught Error: Could not find module `rsvp` imported from `fetch`
```

I tried to also install `rsvp` (`yarn add rsvp --dev`) in my app but it didn't help.

**Comment by rwjblue** [comment]
@mydea - What ember-source version?

**Comment by mydea** [comment]
ember-source@3.27.3, and Embroider at 0.41.0.

**Comment by mydea** [comment]
I played around with it a bit, trying to make it recognize `rsvp`, but couldn't get it to work. I ended up with this kind of workaround (which is decent I'd say, but also rather circumvents the problem) here: https://github.com/ember-cli/ember-fetch/pull/623

**Comment by rwjblue** [comment]
Hmm, Embroider should be able to resolve `rsvp` module if imported directly. I wonder which of the compat flags you have setup? If you have most of the strictnesss / compat flags setup, I'd bet that the issue is that this isn't a "real" module (we are defining an AMD module) so it doesn't get replaced by the webpack require mechanism (and with strictness setup, we don't eagerly `define` all the modules for compatibility purposes anymore).

**Comment by mydea** [comment]
It happens once I switch `staticAddonTrees` on!
